default:
  image: debian:bookworm-slim

before_script:
  - apt-get update --yes
  - apt-get install pipx --yes
  - PIPX_BIN_DIR=/usr/local/bin PIPX_HOME=/opt/pipx pipx install hatch

stages:
  - test
  - style
  - build

test:
  stage: test
  script:
    - hatch test

style:typing:
  stage: style
  script:
    - hatch run style:typing

style:fmt:
  stage: style
  script:
    - hatch fmt

style:codespell:
  stage: style
  script:
    - apt-get install codespell --yes
    - codespell .

build:whl:
  stage: build
  script:
    - hatch build
